/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class foo_MatrixMultiplyJNI */

#ifndef _Included_foo_MatrixMultiplyJNI
#define _Included_foo_MatrixMultiplyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     foo_MatrixMultiplyJNI
 * Method:    matrixMultiply
 * Signature: (IIII[D[D[D)V
 */
JNIEXPORT void JNICALL Java_foo_MatrixMultiplyJNI_matrixMultiply
  (JNIEnv *, jobject, jint, jint, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     foo_MatrixMultiplyJNI
 * Method:    isGPUAvailable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_foo_MatrixMultiplyJNI_isGPUAvailable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
